# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
