# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_review', '0002_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='users',
        ),
    ]
