# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_review', '0003_auto_20170625_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='books',
            field=models.ManyToManyField(to='belt_review.Book'),
        ),
        migrations.AlterField(
            model_name='review',
            name='users',
            field=models.ManyToManyField(to='belt_review.User'),
        ),
    ]
