# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_remove_courses_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
